Slot for play button to allow setting accessibility attributes
radiofrance/svelte-youtube-lite pull request #2
Opened 2024-10-19 04:17 UTC by ddikman

# Overview

Adds so that you can override the play button with accessibility attributes as you need.

Example usage (added to example page):

```svelte
  <h2>With custom aria label button</h2>
	<Youtube id="aYtE6XE6b_s" showTitle={false}>
    <slot name="playButton">
      <PlayButton ariaLabel="Custom play button" />
    </slot>
  </Youtube>

	<h2>With custom button</h2>
	<Youtube id="aYtE6XE6b_s" showTitle={false}>
    <slot name="playButton">
      <button>A completely custom button</button>
    </slot>
  </Youtube>
```

2024-10-20 01:53 UTC, romaindurand requested changes
Thanks for your contribution ! 😍 
I just tweaked your examples a bit because it didn't work as expected when I ran `pnpm dev`, tell me if it works for you :)

2024-10-20 01:53 UTC, romaindurand commented on src/routes/+page.svelte
> +    </slot>
To make the examples work, slots must be used directly on the element

```suggestion
    <PlayButton slot="playButton" ariaLabel="Custom play button" />
```

2024-10-20 01:53 UTC, romaindurand commented on src/routes/+page.svelte
> +    </slot>
```suggestion
    <button slot="playButton>A completely custom button</button>
```

2024-10-22 08:55 UTC, ddikman commented
@romaindurand thank you for checking it! I was sloppy when I tested my local version and didn't realise it actually didn't apply. I integrated your changes and styled the custom button a bit further to match the others.

2024-10-22 09:13 UTC, merged

2024-10-22 09:21 UTC, romaindurand commented
@ddikman 🎉 
![image](https://github.com/user-attachments/assets/ec6a95f3-355a-4b7c-b44e-18ad68e3156f)